name: Gitbook PR

on:
  push:
    branches:
      - gitbook

  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  creat-gitbook-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Fetch&merge main branch
        run: |
          git fetch
          git reset --hard origin/main
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          branch: gitbook
          base: main
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"

