name: Gitbook rebase with main

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  gitbook-rebase-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Rebase main branch
        run: |
          git config --global user.email "bot@huma.finance"
          git config --global user.name "Huma bot"
          git fetch
          git checkout gitbook
          git merge origin/main --commit
          git push
