name: Gitbook rebase with main

on:
  workflow_dispatch:

jobs:
  gitbook-rebase-main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Rebase main branch
        run: |
          git config --global user.email "bot@huma.finance"
          git config --global user.name "Huma bot"
          git fetch
          git checkout gitbook
          git reset --hard origin/main
          git push --force
